import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {TilesRenderer} from '3d-tiles-renderer/three';
import {GoogleCloudAuthPlugin} from '3d-tiles-renderer/plugins';
import {Sky} from 'three/addons/objects/Sky.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {SMAAPass} from 'three/addons/postprocessing/SMAAPass.js';

const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const toRad=d=>d*Math.PI/180;
const haversine=(a,b)=>{const R=6371000,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x));};
function metrics(points){let d=0;const cumulative=[0];for(let i=1;i<points.length;i++){d+=haversine(points[i-1],points[i]);cumulative.push(d)}return{distance:d,cumulative}}
function interp(points,cumulative,d){if(!points.length)return null;if(points.length===1)return points[0];d=clamp(d,0,cumulative.at(-1));let i=1;while(i<cumulative.length&&cumulative[i]<d)i++;const lo=cumulative[i-1],hi=cumulative[i],t=(d-lo)/Math.max(1,hi-lo),a=points[i-1],b=points[i];return{lat:a.lat+(b.lat-a.lat)*t,lng:a.lng+(b.lng-a.lng)*t}}
function mulberry32(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function makeRouteData(points,terrain){
  if(points.length<2)return null;
  const origin=points[0],lat0=toRad(origin.lat),mLat=111132.92,mLon=111412.84*Math.cos(lat0),rm=metrics(points);
  const elev=d=>{if(terrain.length<2)return 0;let i=1;while(i<terrain.length&&terrain[i].d<d)i++;i=clamp(i,1,terrain.length-1);const a=terrain[i-1],b=terrain[i],t=(d-a.d)/Math.max(1,b.d-a.d);return (a.elev+(b.elev-a.elev)*t)-terrain[0].elev};
  const count=Math.min(2200,Math.max(120,Math.ceil(rm.distance/8))),pts=[];
  for(let i=0;i<count;i++){const d=rm.distance*i/(count-1),p=interp(points,rm.cumulative,d);pts.push(new THREE.Vector3((p.lng-origin.lng)*mLon,elev(d),(p.lat-origin.lat)*mLat));}
  const curve=new THREE.CatmullRomCurve3(pts,false,'centripetal',.08);curve.arcLengthDivisions=Math.min(8000,Math.max(600,pts.length*4));curve.updateArcLengths();
  return{origin,curve,distance:rm.distance,cumulative:rm.cumulative};
}
function frameAt(curve,u){const p=curve.getPointAt(clamp(u,0,1)),t=curve.getTangentAt(clamp(u,0,1)).normalize(),up0=new THREE.Vector3(0,1,0),right=new THREE.Vector3().crossVectors(t,up0).normalize();if(right.lengthSq()<.2)right.set(1,0,0);const up=new THREE.Vector3().crossVectors(right,t).normalize();return{p,t,right,up}}
function ribbon(curve,width,step=5,yOffset=0){const len=curve.getLength(),n=Math.max(8,Math.ceil(len/step)),pos=[],uv=[],idx=[];for(let i=0;i<=n;i++){const f=frameAt(curve,i/n),p=f.p.clone().addScaledVector(f.up,yOffset),a=p.clone().addScaledVector(f.right,-width/2),b=p.clone().addScaledVector(f.right,width/2);pos.push(a.x,a.y,a.z,b.x,b.y,b.z);uv.push(0,i/2,1,i/2);if(i<n){const k=i*2;idx.push(k,k+1,k+2,k+1,k+3,k+2)}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
function tube(curve,rad,segments=1000,sides=8){return new THREE.TubeGeometry(curve,Math.min(segments,Math.max(80,Math.ceil(curve.getLength()/2.2))),rad,sides,false)}
function localCurveOffset(curve,offset,y=0){const n=Math.min(1800,Math.max(100,Math.ceil(curve.getLength()/5))),pts=[];for(let i=0;i<=n;i++){const f=frameAt(curve,i/n);pts.push(f.p.clone().addScaledVector(f.right,offset).addScaledVector(f.up,y))}return new THREE.CatmullRomCurve3(pts,false,'centripetal',.05)}
function disposeTree(o){o?.traverse?.(x=>{x.geometry?.dispose?.();if(Array.isArray(x.material))x.material.forEach(m=>{m.map?.dispose?.();m.dispose?.()});else{x.material?.map?.dispose?.();x.material?.dispose?.()}})}
function canvasTexture(kind,repeatX=1,repeatY=1){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),r=mulberry32(kind.length*991);
  if(kind==='ballast'){x.fillStyle='#77756f';x.fillRect(0,0,256,256);for(let i=0;i<2600;i++){const g=70+Math.floor(r()*90);x.fillStyle=`rgb(${g},${g},${g-5})`;const s=1+r()*4;x.fillRect(r()*256,r()*256,s,s)}}
  else if(kind==='grass'){x.fillStyle='#536f3d';x.fillRect(0,0,256,256);for(let i=0;i<1800;i++){x.fillStyle=r()>.5?'#66884d':'#425d33';x.fillRect(r()*256,r()*256,1+r()*3,1+r()*5)}}
  else if(kind==='concrete'){x.fillStyle='#777a78';x.fillRect(0,0,256,256);for(let i=0;i<900;i++){const g=95+Math.floor(r()*50);x.fillStyle=`rgb(${g},${g},${g})`;x.fillRect(r()*256,r()*256,1,1)}}
  else if(kind==='metal'){const grad=x.createLinearGradient(0,0,256,0);grad.addColorStop(0,'#555b5e');grad.addColorStop(.45,'#d0d3d2');grad.addColorStop(.55,'#808689');grad.addColorStop(1,'#4c5154');x.fillStyle=grad;x.fillRect(0,0,256,256)}
  const tex=new THREE.CanvasTexture(c);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(repeatX,repeatY);tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=4;return tex;
}
function standardMat(opts={}){const m=new THREE.MeshStandardMaterial(opts);if(m.map)m.map.colorSpace=THREE.SRGBColorSpace;return m}
function physicalMat(opts={}){const m=new THREE.MeshPhysicalMaterial(opts);if(m.map)m.map.colorSpace=THREE.SRGBColorSpace;return m}
function carBodyGeometry(len=22,w=3.05,h=3.6){const s=new THREE.Shape();s.moveTo(-w/2,.35);s.lineTo(-w/2,h-.55);s.quadraticCurveTo(-w/2,h,-w/2+.55,h);s.lineTo(w/2-.55,h);s.quadraticCurveTo(w/2,h,w/2,h-.55);s.lineTo(w/2,.35);s.lineTo(w/2-.18,0);s.lineTo(-w/2+.18,0);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:len,bevelEnabled:true,bevelThickness:.05,bevelSize:.05,bevelSegments:2});g.translate(0,0,-len/2);g.computeVertexNormals();return g}
function wedgeGeometry(w,h,d){const v=new Float32Array([-w/2,0,0,w/2,0,0,w/2,h,0,-w/2,h,0,-w/2,0,-d,w/2,0,-d,w/2,h*.68,-d,-w/2,h*.68,-d]);const idx=[0,1,2,0,2,3,4,6,5,4,7,6,0,4,5,0,5,1,3,2,6,3,6,7,1,5,6,1,6,2,0,3,7,0,7,4];const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();return g}
function addBogies(car,len,dark){for(const z of [-len*.31,len*.31]){const bogie=new THREE.Group();const frame=new THREE.Mesh(new THREE.BoxGeometry(2.3,.25,2.5),dark);frame.position.y=.58;bogie.add(frame);for(const zz of [-.75,.75])for(const x of [-1.12,1.12]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.43,.43,.22,20),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.43,z+zz);car.add(wheel)}car.add(bogie)}}
function addTrain(group,train,full=true){
  const bodyMat=physicalMat({color:new THREE.Color(train.bodyColor||'#d6aa43'),metalness:.72,roughness:.23,clearcoat:.7,clearcoatRoughness:.16}),stripeMat=physicalMat({color:new THREE.Color(train.stripeColor||'#3de2b1'),metalness:.48,roughness:.25,clearcoat:.45}),glass=physicalMat({color:0x163b50,metalness:.05,roughness:.04,transmission:.18,transparent:true,opacity:.72,ior:1.45,clearcoat:1,clearcoatRoughness:.05}),dark=standardMat({color:0x111416,metalness:.72,roughness:.32}),trim=standardMat({color:0xcbd0d2,metalness:.82,roughness:.2});
  const count=full?Math.min(train.carCount+1,14):Math.min(train.carCount+1,8);
  for(let i=0;i<count;i++){
    const car=new THREE.Group(),isLead=i===0,len=isLead?20.5:23.5;const body=new THREE.Mesh(carBodyGeometry(len,3.08,3.55),bodyMat);body.position.y=.76;body.castShadow=body.receiveShadow=true;car.add(body);
    const roof=new THREE.Mesh(new THREE.BoxGeometry(2.7,.18,len*.93),dark);roof.position.set(0,4.27,0);roof.castShadow=true;car.add(roof);
    const stripe=new THREE.Mesh(new THREE.BoxGeometry(3.105,.11,len*.94),stripeMat);stripe.position.set(0,2.02,0);car.add(stripe);
    for(const side of [-1,1]){for(let z=-len/2+2.2;z<len/2-1.7;z+=2.7){const win=new THREE.Mesh(new THREE.BoxGeometry(.028,1.05,1.55),glass);win.position.set(side*1.551,2.92,z);car.add(win)}for(let z=-len/2+1.15;z<len/2-1;z+=6.8){const door=new THREE.Mesh(new THREE.BoxGeometry(.035,2.15,1.05),trim);door.position.set(side*1.555,2.15,z);car.add(door)}}
    if(isLead){const nose=new THREE.Mesh(wedgeGeometry(3.0,2.8,1.5),bodyMat);nose.position.set(0,1.06,-len/2);nose.rotation.y=Math.PI;car.add(nose);const windshield=new THREE.Mesh(new THREE.PlaneGeometry(2.35,1.18),glass);windshield.position.set(0,3.12,-len/2-1.28);windshield.rotation.x=-.18;car.add(windshield);for(const x of [-.92,.92]){const lampMesh=new THREE.Mesh(new THREE.CylinderGeometry(.14,.14,.07,18),new THREE.MeshBasicMaterial({color:0xfff4cf,toneMapped:false}));lampMesh.rotation.x=Math.PI/2;lampMesh.position.set(x,1.62,-len/2-1.43);car.add(lampMesh);const l=new THREE.SpotLight(0xfff3d6,14,115,.18,.35,1.2);l.position.set(x,1.7,-len/2-1.35);l.target.position.set(x,0,-len/2-45);car.add(l,l.target)}}
    addBogies(car,len,dark);car.userData.offset=i*25;group.add(car);
  }
  return group;
}
function placeObjectOnTrack(obj,curve,distance,d,side=0,y=0){const f=frameAt(curve,clamp(d/distance,0,1));obj.position.copy(f.p).addScaledVector(f.right,side).addScaledVector(f.up,y);obj.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(f.right,f.up,f.t.clone().negate()));}

function distanceToPolylineXZ(x,z,curve,distance){let best=Infinity;const n=Math.min(700,Math.max(80,Math.ceil(distance/25)));let prev=curve.getPointAt(0);for(let i=1;i<=n;i++){const cur=curve.getPointAt(i/n),vx=cur.x-prev.x,vz=cur.z-prev.z,wx=x-prev.x,wz=z-prev.z,t=clamp((wx*vx+wz*vz)/Math.max(.001,vx*vx+vz*vz),0,1),qx=prev.x+vx*t,qz=prev.z+vz*t;best=Math.min(best,Math.hypot(x-qx,z-qz));prev=cur}return best}
function roofGeometryForFootprint(shape,height,roofShape){const settings={depth:height,bevelEnabled:false};const g=new THREE.ExtrudeGeometry(shape,settings);g.rotateX(Math.PI/2);return g}
async function addRealWorldBuildings(root,data,route,quality){if(!route?.length||quality<2)return()=>{};const minLat=Math.min(...route.map(p=>p.lat)),maxLat=Math.max(...route.map(p=>p.lat)),minLng=Math.min(...route.map(p=>p.lng)),maxLng=Math.max(...route.map(p=>p.lng)),span=Math.max(maxLat-minLat,maxLng-minLng);if(span>.32)return()=>{};const pad=.0045,bbox=`${minLat-pad},${minLng-pad},${maxLat+pad},${maxLng+pad}`,q=`[out:json][timeout:22];way["building"](${bbox});out tags geom 900;`;const controller=new AbortController();try{const r=await fetch(`https://overpass-api.de/api/interpreter?data=${encodeURIComponent(q)}`,{signal:controller.signal});if(!r.ok)return()=>controller.abort();const j=await r.json(),grp=new THREE.Group();grp.name='real-world-buildings';const origin=data.origin,lat0=toRad(origin.lat),mLat=111132.92,mLon=111412.84*Math.cos(lat0),max=quality>=4?850:quality>=3?520:260;let count=0;for(const el of j.elements||[]){if(count>=max||!el.geometry?.length)continue;const pts=el.geometry.map(p=>new THREE.Vector2((p.lon-origin.lng)*mLon,(p.lat-origin.lat)*mLat));if(pts.length<4)continue;let cx=0,cz=0;for(const v of pts){cx+=v.x;cz+=v.y}cx/=pts.length;cz/=pts.length;let rad=0;for(const v of pts)rad=Math.max(rad,Math.hypot(v.x-cx,v.y-cz));const clearance=distanceToPolylineXZ(cx,cz,data.curve,data.distance)-rad;if(clearance<3.048)continue;const levels=Number(el.tags?.['building:levels']),tagHeight=parseFloat(el.tags?.height),height=clamp(Number.isFinite(tagHeight)?tagHeight:Number.isFinite(levels)?levels*3.15:7+(el.id%7)*2.1,3,95),shape=new THREE.Shape();pts.forEach((v,i)=>i?shape.lineTo(v.x-cx,v.y-cz):shape.moveTo(v.x-cx,v.y-cz));shape.closePath();const hue=((el.id||1)%17)/220+.055,mat=physicalMat({color:new THREE.Color().setHSL(hue,.08,.42+((el.id||1)%5)*.055),roughness:.72,metalness:.04,clearcoat:.08}),mesh=new THREE.Mesh(roofGeometryForFootprint(shape,height,el.tags?.['roof:shape']),mat);mesh.position.set(cx,0,cz);mesh.castShadow=quality>=4;mesh.receiveShadow=true;grp.add(mesh);count++}root.add(grp)}catch(e){if(e.name!=='AbortError')console.warn('Real building stream unavailable',e)}return()=>controller.abort()}

function addTree(root,curve,distance,d,side,scale=1){const grp=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13,.18,2.4,7),standardMat({color:0x59402a,roughness:1}));trunk.position.y=1.2;grp.add(trunk);const leavesMat=standardMat({color:side>0?0x385c2b:0x466b35,roughness:1});for(const [y,r] of [[2.4,1.15],[3.15,.95],[3.8,.68]]){const m=new THREE.Mesh(new THREE.ConeGeometry(r,1.7,8),leavesMat);m.position.y=y;grp.add(m)}grp.scale.setScalar(scale);placeObjectOnTrack(grp,curve,distance,d,side,-.4);root.add(grp)}
function addBuilding(root,curve,distance,d,side,rng){const w=6+rng()*14,h=5+rng()*24,l=8+rng()*18,grp=new THREE.Group(),mat=standardMat({color:new THREE.Color().setHSL(.07+rng()*.08,.08,.38+rng()*.25),roughness:.88}),roof=standardMat({color:0x363b3d,roughness:.8});const b=new THREE.Mesh(new THREE.BoxGeometry(w,h,l),mat);b.position.y=h/2;grp.add(b);const r=new THREE.Mesh(new THREE.BoxGeometry(w+.25,.3,l+.25),roof);r.position.y=h+.15;grp.add(r);const winMat=new THREE.MeshBasicMaterial({color:rng()>.5?0xb6d7e2:0xffdda3});for(const z of [-l*.25,l*.25])for(let y=2;y<h-1;y+=3.1){const win=new THREE.Mesh(new THREE.PlaneGeometry(w*.55,.8),winMat);win.position.set(0,y,z+(z<0?-.01:.01));win.rotation.y=z<0?Math.PI:0;grp.add(win)}placeObjectOnTrack(grp,curve,distance,d,side,-.55);root.add(grp)}
function addFence(root,curve,distance,side){const postMat=standardMat({color:0x4b5052,metalness:.62,roughness:.4}),wireMat=standardMat({color:0x313638,metalness:.8,roughness:.28});for(let d=0;d<distance;d+=18){const g=new THREE.Group();const p=new THREE.Mesh(new THREE.BoxGeometry(.08,1.25,.08),postMat);p.position.y=.62;g.add(p);for(const y of [.35,.72,1.08]){const w=new THREE.Mesh(new THREE.BoxGeometry(.025,.025,18),wireMat);w.position.set(0,y,9);g.add(w)}placeObjectOnTrack(g,curve,distance,d,side,-.2);root.add(g)}}
function addTracksideWeeds(root,curve,distance,rng){const mat=standardMat({color:0x4b6d32,roughness:1,side:THREE.DoubleSide}),geo=new THREE.PlaneGeometry(.65,1.35);const count=Math.min(1800,Math.floor(distance/5)),mesh=new THREE.InstancedMesh(geo,mat,count),dummy=new THREE.Object3D();for(let i=0;i<count;i++){const d=rng()*distance,f=frameAt(curve,d/distance),side=(rng()>.5?1:-1)*(2.7+rng()*8);dummy.position.copy(f.p).addScaledVector(f.right,side).addScaledVector(f.up,-.15);dummy.scale.set(.4+rng()*.8,.55+rng()*1.35,.4+rng()*.8);dummy.rotation.y=rng()*Math.PI;dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix)}mesh.instanceMatrix.needsUpdate=true;root.add(mesh)}
function addLinesideCabinet(root,curve,distance,d,side){const g=new THREE.Group(),m=standardMat({color:0xb8bab5,metalness:.25,roughness:.75}),base=standardMat({color:0x555958,roughness:.9});const b=new THREE.Mesh(new THREE.BoxGeometry(.85,1.2,.52),m);b.position.y=.72;g.add(b);const pl=new THREE.Mesh(new THREE.BoxGeometry(1.05,.18,.72),base);pl.position.y=.09;g.add(pl);placeObjectOnTrack(g,curve,distance,d,side,0);root.add(g)}
function addDistantTerrain(root,curve,distance,rng){for(const side of [-1,1])for(let d=0;d<distance;d+=260){const g=new THREE.Group(),h=15+rng()*55,w=80+rng()*160,dep=90+rng()*190,mat=standardMat({color:new THREE.Color().setHSL(.29,.18,.26+rng()*.12),roughness:1});const hill=new THREE.Mesh(new THREE.ConeGeometry(w*.45,h,7),mat);hill.scale.z=dep/w;hill.position.y=h*.42;g.add(hill);placeObjectOnTrack(g,curve,distance,d+rng()*120,side*(90+rng()*160),-4);root.add(g)}}
function addStation(root,curve,distance,s,idx,mode){const grp=new THREE.Group(),concrete=standardMat({map:canvasTexture('concrete',3,8),roughness:.95}),edge=standardMat({color:0xe4cd52,roughness:.78}),steel=standardMat({color:0x555f63,metalness:.65,roughness:.32}),roofMat=standardMat({color:mode==='subway'?0x6d7478:0x2e3a3f,metalness:.48,roughness:.35});
  const plat=new THREE.Mesh(new THREE.BoxGeometry(4.2,.62,145),concrete);plat.position.y=.2;plat.receiveShadow=true;grp.add(plat);const tactile=new THREE.Mesh(new THREE.BoxGeometry(.42,.08,143),edge);tactile.position.set(-1.78,.55,0);grp.add(tactile);
  const canopy=new THREE.Mesh(new THREE.BoxGeometry(3.35,.16,72),roofMat);canopy.position.set(0,3.8,0);grp.add(canopy);for(let z=-32;z<=32;z+=16){const post=new THREE.Mesh(new THREE.CylinderGeometry(.09,.09,3.5,10),steel);post.position.set(.4,2.05,z);grp.add(post);const lamp=new THREE.PointLight(0xffedcc,mode==='subway'?4:1.1,18);lamp.position.set(-.4,3.55,z);grp.add(lamp)}
  for(const z of [-24,0,24]){const bench=new THREE.Mesh(new THREE.BoxGeometry(1.9,.12,.48),standardMat({color:0x65462c,roughness:.75}));bench.position.set(.65,.92,z);grp.add(bench)}placeObjectOnTrack(grp,curve,distance,s.d,3.85,0);root.add(grp);
  const cv=document.createElement('canvas');cv.width=1024;cv.height=192;const c=cv.getContext('2d');c.fillStyle='#18252c';c.fillRect(0,0,1024,192);c.fillStyle='#f3f6f7';c.font='700 66px system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(s.name,512,96);const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;const sign=new THREE.Mesh(new THREE.PlaneGeometry(6.8,1.27),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));placeObjectOnTrack(sign,curve,distance,s.d+18,2.1,2.4);root.add(sign)}
function addSignal(root,curve,distance,d){const grp=new THREE.Group(),steel=standardMat({color:0x353b3d,metalness:.68,roughness:.32});const post=new THREE.Mesh(new THREE.CylinderGeometry(.07,.09,4.1,10),steel);post.position.y=2.05;grp.add(post);const head=new THREE.Mesh(new THREE.BoxGeometry(.65,1.45,.48),steel);head.position.y=4.15;grp.add(head);for(const [y,col] of [[4.52,0x291010],[4.15,0x5c4211],[3.78,0x43ff72]]){const lamp=new THREE.Mesh(new THREE.SphereGeometry(.15,16,10),new THREE.MeshBasicMaterial({color:col}));lamp.position.set(0,y,-.26);grp.add(lamp)}placeObjectOnTrack(grp,curve,distance,d,-2.45,0);root.add(grp)}
function buildWorld(scene,data,{mode,stations,train,quality=3,trackCount=2}){const root=new THREE.Group();scene.add(root);const {curve,distance}=data,rng=mulberry32(Math.floor(distance)+stations.length*177);
  const groundTex=canvasTexture('grass',10,120),ballastTex=canvasTexture('ballast',3,80),concreteTex=canvasTexture('concrete',4,60),railTex=canvasTexture('metal',1,30);
  const groundMat=standardMat({map:groundTex,roughness:1}),ballastMat=standardMat({map:mode==='subway'?concreteTex:ballastTex,roughness:.95}),railMat=standardMat({map:railTex,color:0xbfc3c1,metalness:.92,roughness:.2}),sleeperMat=standardMat({color:mode==='subway'?0x777b79:0x4d3b2d,roughness:.9});
  if(mode==='surface'){
    const land=new THREE.Mesh(ribbon(curve,260,16,-.7),groundMat);land.receiveShadow=true;root.add(land);
    const embank=new THREE.Mesh(ribbon(curve,9.2,5,-.32),standardMat({color:0x5a5853,roughness:1}));embank.receiveShadow=true;root.add(embank);
    const ballast=new THREE.Mesh(ribbon(curve,4.8,3,-.12),ballastMat);ballast.receiveShadow=true;root.add(ballast);
  }else{
    const shell=new THREE.Mesh(tube(curve,5.25,1500,20),standardMat({map:concreteTex,color:0x5c6060,roughness:.92,side:THREE.BackSide}));root.add(shell);
    const invert=new THREE.Mesh(ribbon(curve,7.8,3,-2.35),standardMat({color:0x404344,roughness:1}));root.add(invert);
    for(let d=0;d<distance;d+=8){const f=frameAt(curve,d/distance),ring=new THREE.Mesh(new THREE.TorusGeometry(5.12,.055,6,24),standardMat({color:0x707677,metalness:.25,roughness:.55}));ring.position.copy(f.p);ring.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),f.t);root.add(ring)}
    for(let d=12;d<distance;d+=22){for(const side of [-1,1]){const light=new THREE.PointLight(0xffe8b6,2.5,19,1.7);placeObjectOnTrack(light,curve,distance,d,side*3.6,2.8);root.add(light)}}
  }
  for(const off of [-.7175,.7175]){const rc=localCurveOffset(curve,off,.055),rail=new THREE.Mesh(tube(rc,.078,1600,8),railMat);rail.castShadow=true;root.add(rail)}
  const spacing=.62,nSleep=Math.min(11000,Math.max(1,Math.floor(distance/spacing))),sleepGeo=new THREE.BoxGeometry(2.65,.16,.24),sleep=new THREE.InstancedMesh(sleepGeo,sleeperMat,nSleep),dummy=new THREE.Object3D();sleep.castShadow=sleep.receiveShadow=true;
  for(let i=0;i<nSleep;i++){const f=frameAt(curve,i/Math.max(1,nSleep-1));dummy.position.copy(f.p).addScaledVector(f.up,-.055);dummy.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(f.right,f.up,f.t));dummy.updateMatrix();sleep.setMatrixAt(i,dummy.matrix)}sleep.instanceMatrix.needsUpdate=true;root.add(sleep);
  if(trackCount===2){for(const center of [-4.5,4.5]){for(const off of [-.7175,.7175]){const rc=localCurveOffset(curve,center+off,.055),rail=new THREE.Mesh(tube(rc,.078,1600,8),railMat);rail.castShadow=true;root.add(rail)}const bed=new THREE.Mesh(ribbon(localCurveOffset(curve,center,0),4.8,3,-.12),ballastMat);bed.receiveShadow=true;root.add(bed)}}
  if(mode==='surface'){
    const density=[.16,.28,.45,.68,.9,1.15][quality]||.68;const sceneryCount=Math.min(1800,Math.floor(distance/24*density));for(let i=0;i<sceneryCount;i++){const d=i*distance/Math.max(1,sceneryCount-1)+rng()*14,side=(rng()>.5?1:-1)*(9+rng()*105);if(stations.some(s=>Math.abs(s.d-d)<120))continue;if(rng()<.72)addTree(root,curve,distance,d,side,.65+rng()*1.5);else addBuilding(root,curve,distance,d,(side<0?-1:1)*(18+rng()*96),rng)}
    if(quality>=1)addFence(root,curve,distance,-7.4);if(quality>=1)addFence(root,curve,distance,7.4);if(quality>=2)addTracksideWeeds(root,curve,distance,rng);if(quality>=2)addDistantTerrain(root,curve,distance,rng);for(let d=180;d<distance;d+=quality>=3?340:520)addLinesideCabinet(root,curve,distance,d,rng()>.5?5.8:-5.8);
  }
  if(mode==='surface'&&train.kind==='electric'){
    const poleMat=standardMat({color:0x5c6365,metalness:.82,roughness:.25}),wireMat=new THREE.MeshStandardMaterial({color:0x242829,metalness:.8,roughness:.25}),poles=Math.min(900,Math.floor(distance/42));for(let i=0;i<=poles;i++){const d=i*distance/Math.max(1,poles),grp=new THREE.Group(),pole=new THREE.Mesh(new THREE.CylinderGeometry(.055,.075,7,8),poleMat);pole.position.y=3.5;grp.add(pole);const mast=new THREE.Mesh(new THREE.BoxGeometry(3.4,.065,.07),poleMat);mast.position.set(1.25,6.1,0);grp.add(mast);placeObjectOnTrack(grp,curve,distance,d,-2.25,0);root.add(grp)}const wireCurve=localCurveOffset(curve,0,5.7),wire=new THREE.Mesh(tube(wireCurve,.014,1800,4),wireMat);root.add(wire);
  }
  stations.forEach((s,i)=>addStation(root,curve,distance,s,i,mode));for(let d=650;d<distance;d+=950)addSignal(root,curve,distance,d);return root}
const QUALITY_PRESETS=[
  {name:'Performance',scale:.52,shadows:false,shadowSize:0,bloom:false,smaa:false,far:1800},
  {name:'Balanced',scale:.62,shadows:true,shadowSize:512,bloom:false,smaa:false,far:2400},
  {name:'Quality',scale:.72,shadows:true,shadowSize:1024,bloom:true,smaa:false,far:3200},
  {name:'High',scale:.82,shadows:true,shadowSize:1536,bloom:true,smaa:true,far:4200},
  {name:'Ultra',scale:.92,shadows:true,shadowSize:2048,bloom:true,smaa:true,far:5200},
  {name:'Cinematic',scale:1.0,shadows:true,shadowSize:3072,bloom:true,smaa:true,far:6500}
];
export function getDeviceGraphicsInfo(){
  const canvas=document.createElement('canvas'); const gl=canvas.getContext('webgl2')||canvas.getContext('webgl');
  let gpu='Unavailable',vendor='Unavailable',maxTexture=0,maxSamples=0;
  if(gl){maxTexture=gl.getParameter(gl.MAX_TEXTURE_SIZE)||0;maxSamples=gl.MAX_SAMPLES?gl.getParameter(gl.MAX_SAMPLES)||0:0;const dbg=gl.getExtension('WEBGL_debug_renderer_info');if(dbg){gpu=gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL)||'Hidden by browser';vendor=gl.getParameter(dbg.UNMASKED_VENDOR_WEBGL)||'Hidden by browser'}else{gpu=gl.getParameter(gl.RENDERER)||'Browser-hidden GPU';vendor=gl.getParameter(gl.VENDOR)||'Browser-hidden vendor'}}
  const cores=navigator.hardwareConcurrency||0, memory=navigator.deviceMemory||0, dpr=window.devicePixelRatio||1, pixels=screen.width*screen.height*dpr*dpr, touch=navigator.maxTouchPoints||0;
  let score=2;if(cores>=8)score++;if(cores>=12)score++;if(memory>=8)score++;if(memory>0&&memory<=4)score--;if(pixels>7_000_000)score--;if(maxTexture>=16384)score++;if(/Apple|M[1234]|RTX|Radeon RX|Arc/i.test(gpu))score++;if(/Mali|Adreno 6|PowerVR/i.test(gpu))score--;score=Math.max(0,Math.min(5,score));
  return{cores,memory,dpr,pixels,touch,gpu,vendor,maxTexture,maxSamples,recommendedLevel:score};
}

function ecefLocalMatrix(origin){
  const lat=toRad(origin.lat),lon=toRad(origin.lng),a=6378137,e2=6.69437999014e-3,N=a/Math.sqrt(1-e2*Math.sin(lat)**2);
  const O=new THREE.Vector3(N*Math.cos(lat)*Math.cos(lon),N*Math.cos(lat)*Math.sin(lon),N*(1-e2)*Math.sin(lat));
  const east=new THREE.Vector3(-Math.sin(lon),Math.cos(lon),0),up=new THREE.Vector3(Math.cos(lat)*Math.cos(lon),Math.cos(lat)*Math.sin(lon),Math.sin(lat));
  const south=new THREE.Vector3(Math.sin(lat)*Math.cos(lon),Math.sin(lat)*Math.sin(lon),-Math.cos(lat));
  return new THREE.Matrix4().set(east.x,east.y,east.z,-east.dot(O),up.x,up.y,up.z,-up.dot(O),south.x,south.y,south.z,-south.dot(O),0,0,0,1);
}
function addGooglePhotogrammetry(scene,data,camera,renderer,key,q){
  if(!key||!data?.origin)return null;
  try{
    const tiles=new TilesRenderer('https://tile.googleapis.com/v1/3dtiles/root.json');
    tiles.registerPlugin(new GoogleCloudAuthPlugin({apiToken:key}));
    tiles.setCamera(camera); tiles.setResolutionFromRenderer(camera,renderer);
    tiles.group.matrixAutoUpdate=false; tiles.group.matrix.copy(ecefLocalMatrix(data.origin));
    tiles.errorTarget=q.name==='Cinematic'?3:q.name==='Ultra'?5:q.name==='High'?7:11;
    scene.add(tiles.group); return tiles;
  }catch(e){console.warn('Photogrammetry unavailable',e);return null}
}
function createRenderer(el,q){const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',stencil:false});renderer.setPixelRatio(Math.min((window.devicePixelRatio||1)*q.scale,2));renderer.setSize(el.clientWidth,el.clientHeight,false);renderer.shadowMap.enabled=q.shadows;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;el.appendChild(renderer.domElement);return renderer}
function makeComposer(renderer,scene,camera,w,h,q){const composer=new EffectComposer(renderer);composer.setPixelRatio(renderer.getPixelRatio());composer.setSize(w,h);composer.addPass(new RenderPass(scene,camera));if(q.bloom)composer.addPass(new UnrealBloomPass(new THREE.Vector2(w,h),.24,.4,.9));if(q.smaa&&Math.min(w,h)>500)composer.addPass(new SMAAPass(w*renderer.getPixelRatio(),h*renderer.getPixelRatio()));composer.addPass(new OutputPass());return composer}
function addSky(scene,mode,q){if(mode==='subway'){scene.background=new THREE.Color(0x080b0d);scene.fog=new THREE.FogExp2(0x12171a,.005);const hemi=new THREE.HemisphereLight(0x72808a,0x07090a,.38);scene.add(hemi);const sun=new THREE.DirectionalLight(0xbfd4df,.12);sun.position.set(-120,180,-90);scene.add(sun);return sun}const sky=new Sky();sky.scale.setScalar(10000);scene.add(sky);const u=sky.material.uniforms;u.turbidity.value=6.5;u.rayleigh.value=1.65;u.mieCoefficient.value=.0045;u.mieDirectionalG.value=.82;const phi=THREE.MathUtils.degToRad(90-28),theta=THREE.MathUtils.degToRad(225),sunV=new THREE.Vector3().setFromSphericalCoords(1,phi,theta);u.sunPosition.value.copy(sunV);scene.fog=new THREE.FogExp2(0xaec5cf,.00017);const hemi=new THREE.HemisphereLight(0xd8efff,0x556044,1.15);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe3b4,4.6);sun.position.copy(sunV).multiplyScalar(520);sun.castShadow=q.shadows;if(q.shadows){sun.shadow.mapSize.set(q.shadowSize,q.shadowSize);sun.shadow.camera.left=-120;sun.shadow.camera.right=120;sun.shadow.camera.top=120;sun.shadow.camera.bottom=-120;sun.shadow.camera.near=1;sun.shadow.camera.far=1000;sun.shadow.bias=-.00025;sun.shadow.normalBias=.025}scene.add(sun);return sun}
function addCab(camera){const cab=new THREE.Group(),dark=physicalMat({color:0x111517,roughness:.42,metalness:.46,clearcoat:.22}),trim=standardMat({color:0x454d51,roughness:.36,metalness:.5}),panel=physicalMat({color:0x242b2e,roughness:.5,metalness:.32,clearcoat:.18}),rubber=standardMat({color:0x070909,roughness:.9});const dash=new THREE.Mesh(new THREE.BoxGeometry(4.75,.82,1.8),panel);dash.position.set(0,-1.12,-2.05);dash.rotation.x=-.12;cab.add(dash);const brow=new THREE.Mesh(new THREE.BoxGeometry(4.55,.25,.6),dark);brow.position.set(0,.02,-2.62);cab.add(brow);for(const x of [-2.16,2.16]){const pillar=new THREE.Mesh(new THREE.BoxGeometry(.24,4.4,.38),dark);pillar.position.set(x,0,-2.5);cab.add(pillar)}const roof=new THREE.Mesh(new THREE.BoxGeometry(4.65,.28,.68),dark);roof.position.set(0,1.86,-2.48);cab.add(roof);const sill=new THREE.Mesh(new THREE.BoxGeometry(4.65,.28,.5),trim);sill.position.set(0,-.08,-2.62);cab.add(sill);for(const x of [-1.32,0,1.32]){const bezel=new THREE.Mesh(new THREE.BoxGeometry(1.04,.68,.11),rubber);bezel.position.set(x,-.78,-2.89);bezel.rotation.x=-.16;cab.add(bezel);const screen=new THREE.Mesh(new THREE.PlaneGeometry(.87,.5),new THREE.MeshBasicMaterial({color:x===0?0x77d4ff:0x67d6a6,toneMapped:false}));screen.position.set(x,-.77,-2.955);screen.rotation.x=-.16;cab.add(screen)}for(let i=0;i<11;i++){const b=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,.045,12),new THREE.MeshStandardMaterial({color:i%4===0?0xd84a3b:0xb9c1c2,emissive:i%4===0?0x6b110c:0x000000,emissiveIntensity:.45}));b.rotation.x=Math.PI/2;b.position.set(-1.75+i*.35,-1.05,-2.93);cab.add(b)}for(const x of [-1.55,1.55]){const stand=new THREE.Mesh(new THREE.BoxGeometry(.55,1.0,.48),panel);stand.position.set(x,-.88,-1.65);cab.add(stand);const handle=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.68,14),trim);handle.rotation.z=x<0?.48:-.48;handle.position.set(x,-.28,-1.58);cab.add(handle)}const wiperMat=standardMat({color:0x111111,metalness:.65,roughness:.38});for(const x of [-.85,.85]){const arm=new THREE.Mesh(new THREE.BoxGeometry(.035,1.65,.04),wiperMat);arm.position.set(x,.72,-2.72);arm.rotation.z=x<0?-.32:.32;cab.add(arm)}camera.add(cab);return cab}
export function World3D({route,terrain=[],stations=[],train,state,mode,cameraMode='cab',targetFps=45,network=[],trackCount=2,direction='outbound',onGraphicsStats}){const mount=useRef(null),stateRef=useRef(state),infoRef=useRef(null);const [diag,setDiag]=useState('Starting 3D renderer…');if(!infoRef.current)infoRef.current=typeof document!=='undefined'?getDeviceGraphicsInfo():{recommendedLevel:2};const[level,setLevel]=useState(infoRef.current.recommendedLevel);const lowRef=useRef(0),highRef=useRef(0);useEffect(()=>{stateRef.current=state},[state]);useEffect(()=>{const el=mount.current;if(!el||route.length<2)return;const q=QUALITY_PRESETS[level];const renderer=createRenderer(el,q),scene=new THREE.Scene();scene.background=new THREE.Color(mode==='subway'?0x080b0d:0x87b7d6);const sun=addSky(scene,mode,q),camera=new THREE.PerspectiveCamera(cameraMode==='cab'?72:58,el.clientWidth/el.clientHeight,.06,q.far);scene.add(camera);const data=makeRouteData(route,terrain);if(!data){renderer.dispose();return}const world=buildWorld(scene,data,{mode,stations,train,quality:level,trackCount});let googleTiles=null;setDiag('Base 3D scene active • loading photogrammetry…');fetch('/api/config').then(r=>r.json()).then(cfg=>{if(cfg.googleMapTilesKey){googleTiles=addGooglePhotogrammetry(scene,data,camera,renderer,cfg.googleMapTilesKey,q);setDiag(googleTiles?'Base 3D active • Google tiles connecting…':'Base 3D active • Google tiles unavailable')}else setDiag('Base 3D active • no Map Tiles key returned')}).catch(e=>{console.warn(e);setDiag('Base 3D active • config request failed')});let cancelBuildings=()=>{};addRealWorldBuildings(world,data,route,level).then(fn=>{cancelBuildings=fn});const consist=new THREE.Group();addTrain(consist,train,true);scene.add(consist);const aiConsist=new THREE.Group();if(trackCount===2){addTrain(aiConsist,{...train,bodyColor:'#d7d9dc',stripeColor:'#d84b45'},true);scene.add(aiConsist)}const cab=addCab(camera),cars=[...consist.children];let raf;let composer=null,last=performance.now(),samples=[],lastTune=last;
  const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(Math.max(1,w),Math.max(1,h),false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();
  const loop=()=>{const now=performance.now(),dt=Math.max(.001,now-last);last=now;samples.push(dt);if(samples.length>90)samples.shift();const s=stateRef.current||{x:0,v:0},u=clamp(s.x/data.distance,0,1),f=frameAt(data.curve,u);cars.forEach((car,i)=>{const d=clamp(s.x-i*25,0,data.distance),ff=frameAt(data.curve,d/data.distance);car.position.copy(ff.p).addScaledVector(ff.right,trackCount===2?(direction==='outbound'?2.25:-2.25):0).addScaledVector(ff.up,.02);car.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(ff.right,ff.up,ff.t.clone().negate()))});if(trackCount===2){const aiD=(data.distance-((s.t*18+data.distance*.35)%data.distance));[...aiConsist.children].forEach((car,i)=>{const dd=clamp(aiD+i*25,0,data.distance),af=frameAt(data.curve,dd/data.distance);car.position.copy(af.p).addScaledVector(af.right,direction==='outbound'?-2.25:2.25).addScaledVector(af.up,.02);car.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(af.right.clone().negate(),af.up,af.t));});aiConsist.visible=true}consist.visible=cameraMode!=='cab';cab.visible=cameraMode==='cab';const lookD=Math.min(data.distance,s.x+(cameraMode==='cab'?85:120)),lf=frameAt(data.curve,lookD/data.distance);if(cameraMode==='cab'){camera.position.copy(f.p).addScaledVector(f.up,3.45).addScaledVector(f.t,-.5);camera.lookAt(lf.p.clone().addScaledVector(lf.up,2.7));}else if(cameraMode==='chase'){camera.position.copy(f.p).addScaledVector(f.up,7.5).addScaledVector(f.t,-34).addScaledVector(f.right,8.5);camera.lookAt(f.p.clone().addScaledVector(f.up,2.25));}else if(cameraMode==='drone'){camera.position.copy(f.p).addScaledVector(f.up,38).addScaledVector(f.right,42).addScaledVector(f.t,-28);camera.lookAt(f.p.clone().addScaledVector(f.up,1.4))}else{const st=stations.reduce((best,x)=>Math.abs(x.d-s.x)<Math.abs((best?.d??1e12)-s.x)?x:best,stations[0]);const sf=frameAt(data.curve,clamp((st?.d||s.x)/data.distance,0,1));camera.position.copy(sf.p).addScaledVector(sf.right,8).addScaledVector(sf.up,2.1).addScaledVector(sf.t,-18);camera.lookAt(sf.p.clone().addScaledVector(sf.up,2.0))}sun.position.copy(camera.position).add(new THREE.Vector3(-260,420,-140));sun.target.position.copy(f.p);scene.add(sun.target);if(mode==='subway'){const light=camera.userData.headlight||(camera.userData.headlight=new THREE.SpotLight(0xffefcf,28,120,.36,.45,1.4));if(!light.parent){camera.add(light);camera.add(light.target)}light.position.set(0,.4,-.8);light.target.position.set(0,-.5,-80)}googleTiles?.setResolutionFromRenderer?.(camera,renderer);try{googleTiles?.update?.()}catch(e){console.warn('Tiles update failed',e)}renderer.render(scene,camera);
    if(now-lastTune>2400&&samples.length>30){const avg=samples.reduce((a,b)=>a+b,0)/samples.length,fps=1000/avg;onGraphicsStats?.({fps,level,name:q.name,targetFps,device:infoRef.current,renderScale:q.scale,pixelRatio:renderer.getPixelRatio(),triangles:renderer.info.render.triangles,calls:renderer.info.render.calls});if(fps<targetFps*.88){lowRef.current++;highRef.current=0}else if(fps>targetFps*1.15){highRef.current++;lowRef.current=0}else{lowRef.current=highRef.current=0}if(lowRef.current>=2&&level>0){lowRef.current=0;setLevel(x=>x-1)}else if(highRef.current>=3&&level<5){highRef.current=0;setLevel(x=>x+1)}lastTune=now}samples.length&&null;raf=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(raf);cancelBuildings();ro.disconnect();disposeTree(world);disposeTree(consist);disposeTree(aiConsist);googleTiles?.dispose?.();composer?.dispose?.();renderer.dispose();renderer.domElement.remove()};},[route,terrain,stations,train,mode,cameraMode,targetFps,level,onGraphicsStats]);return <div ref={mount} className="three-world"><div className="render-diag">{diag}</div><div className="google-credit">Google Maps • Photorealistic 3D Tiles</div></div>}
export function TrainPreview3D({train}){const mount=useRef(null);useEffect(()=>{const el=mount.current;if(!el)return;const q=QUALITY_PRESETS[3],renderer=createRenderer(el,q),scene=new THREE.Scene();addSky(scene,'surface',q);scene.fog=new THREE.Fog(0xb6cbd2,80,200);const camera=new THREE.PerspectiveCamera(44,el.clientWidth/el.clientHeight,.1,500);camera.position.set(26,9,30);camera.lookAt(0,2,0);const floor=new THREE.Mesh(new THREE.PlaneGeometry(160,90),standardMat({map:canvasTexture('concrete',8,8),roughness:.95}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const g=new THREE.Group();addTrain(g,train,false);g.rotation.y=-Math.PI/2;g.position.set(-((Math.min(train.carCount+1,8)-1)*12),0,0);scene.add(g);let raf,a=-.7;const loop=()=>{a+=.0018;camera.position.x=34*Math.cos(a);camera.position.z=34*Math.sin(a);camera.position.y=8.5;camera.lookAt(0,2.1,0);renderer.render(scene,camera);raf=requestAnimationFrame(loop)};loop();const ro=new ResizeObserver(()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/Math.max(1,el.clientHeight);camera.updateProjectionMatrix()});ro.observe(el);return()=>{cancelAnimationFrame(raf);ro.disconnect();disposeTree(g);renderer.dispose();renderer.domElement.remove()}},[train]);return <div ref={mount} className="train-preview-3d"/>}
